# Dockerfile-postgres
# Use the official PostgreSQL image from Docker Hub
FROM postgres:15

# Set environment variables for PostgreSQL
ENV POSTGRES_DB=LibraryDB
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=password

# Expose the default PostgreSQL port
EXPOSE 5432

# Copy initialization scripts (if any) to the Docker image
# Uncomment the following line if you have SQL scripts to initialize the database
# COPY init.sql /docker-entrypoint-initdb.d/